### ISSUE TITLE
feat: #3 식재료 페이지 제작하기

### ISSUE THREAD

**Issue by ThinkMuk** [24-1-LikePotato/Zipbap-Coin-FE#4]
## Description

<img width="252" alt="스크린샷 2024-07-21 오후 9 15 19" src="https://github.com/user-attachments/assets/779acd12-aeae-4eff-9aca-516e346798df">

상단 검색 바는 홈화면과 식재료 페이지에서만 고정시키기

## To-do

- [x] 네비게이션 바의 식재료 버튼을 클릭하면 해당 날의 추천 식재료를 표시
- [x] 검색창에서 식재료를 검색했을 때 데이터가 있을 경우 로딩되도록 구현하기
- [x] 특정 재료 정보 표시 제작
   - [x] 제목 표시 및 금일 가격, 등 하락율 표시
   - [x] 그래프 구현
      - [x] 월간 그래프로 쉽게 인식할 수 있도록 가독성 향상시키기 (추후 의견 받아보기)
- [x] 관련 레시피 컴포넌트 제작
   - [x] 제목 가로 스크롤 구현 및 버튼들 만들기
   - [x] 클릭한 제목 사진 하단에 표시
   - [x] 하단 레시피 자세히 보기 클릭시 레시피 페이지로 이동

## ETC

-
