### ISSUE TITLE
feat: #2 홈화면 페이지 제작하기

### ISSUE THREAD

**Issue by bomimandoo** [24-1-LikePotato/Zipbap-Coin-FE#5]
## Description

![홈화면](https://github.com/user-attachments/assets/4332e10c-cc1a-499d-beb2-4191e151ee59)

## To-do
- [ ]   검색 창 만들기
    - [ ]  검색시 키워드 param 전송 및 식재료 페이지로 이동
    - [ ]  홈화면, 식재료 화면에만 고정으로 보이게 하기 / 다른 페이지에서는 숨기기(조건문 사용)
- [ ]  오늘의 식재료 컴포넌트 만들기
- [ ]  추천식재료 컴포넌트 만들기
    - [ ]  가로 스크롤 구현
- [ ]  오늘의 집밥
    - [ ]  가로 스크롤 구현
    - [ ]  클릭시 개별 페이지로 이동하도록 param 넘겨주기

## ETC

참고할 사항을 작성하세요.
