### ISSUE TITLE
feat: #1 헤더 컴포넌트들 만들기

### ISSUE THREAD

**Issue by ThinkMuk** [24-1-LikePotato/Zipbap-Coin-FE#6]
## Description
하단 NavBar
<img width="288" alt="스크린샷 2024-07-23 오후 5 22 50" src="https://github.com/user-attachments/assets/da347de1-16fa-4454-b854-712ed2234bed">

상단 Header
<img width="234" alt="스크린샷 2024-07-21 오후 9 18 13" src="https://github.com/user-attachments/assets/c2087110-0b0a-43d6-b0e1-3e70ed2c9b43">
<img width="231" alt="스크린샷 2024-07-21 오후 9 18 23" src="https://github.com/user-attachments/assets/336b2940-402b-4fe2-af66-69055cdd624f">
<img width="234" alt="스크린샷 2024-07-21 오후 9 18 07" src="https://github.com/user-attachments/assets/e2b70129-db76-4485-bbf3-d03105d29979">

## To-do

- [x] 하단 아이콘 클릭시 네비게이션
   - [x] 클릭시 위치한 주소에 따라 아이콘 active
- [x] 상단 제목 표시 헤더에 이동때마다 제목 변경
   - [x] 홈 버튼 클릭시 홈으로 navigate
## ETC

-
