### ISSUE TITLE
feat: #4 냉장고 페이지 제작하기

### ISSUE THREAD

**Issue by ThinkMuk** [24-1-LikePotato/Zipbap-Coin-FE#7]
## Description

![냉장고](https://github.com/user-attachments/assets/c2b75572-ba0e-4e0c-801b-f819fe6ad4d8)

## To-do

- [ ] 내 냉장고 현황 컴포넌트 제작
   - [ ] 등록하기 버튼 클릭시 냉장고 등록하기 페이지로 이동
   - [ ] grid 사용해서 9개 식재료 표시
      - [ ] 가로 스크롤 구현
      - [ ] hover 시 취소 버튼 뜨게 하기
         - [ ] Delete 기능 구현
- [ ] 월간 식재료 구독 컴포넌트 만들기
   - [ ] 버튼 클릭시 alert 뜨게 하기 (임시)

## ETC

-
