### ISSUE TITLE
feat: #5 냉장고 등록1 페이지 제작하기

### ISSUE THREAD

**Issue by taein0926** [24-1-LikePotato/Zipbap-Coin-FE#8]
## Description

![냉장고 - 등록하기 1](https://github.com/user-attachments/assets/a03a9544-dcdd-4452-80fd-6617acd509c8)

## To-do

- [ ]  식재료 입력 컴포넌트 제작
    - [ ]  식재료 입력 요청 텍스트
    - [ ]  식재료 입력 받기
    - [ ]  소비기한 입력 받기
        - [ ]  숫자만 입력 가능하도록 하기
    - [ ]  등록 버튼 만들기
        - [ ]  누르면 입력창의 정보 #6으로 전달
