### ISSUE TITLE
feat: #6 냉장고 등록2 페이지 제작하기

### ISSUE THREAD

**Issue by taein0926** [24-1-LikePotato/Zipbap-Coin-FE#9]
## Description

![냉장고 - 등록하기 2](https://github.com/user-attachments/assets/4cba738a-b747-4db0-b80c-39d4dbf6de6b)

## To-do

- [ ]  식재료 정보 컴포넌트 제작
    - [ ]  #5에서 전달 받은 식재료 정보 텍스트
        - [ ]  타자기 효과주기
    - [ ]  등록 확인 텍스트
    - [ ]  아니오/예 버튼 만들기
        - [ ]  아니오 누를 시 #5로 이동
        - [ ]  예 누를 시 #4에 식재료 정보 전달
